# .streamlit/secrets.toml
#To trun on SQL debugging
debug="OFF"
#OPEN AI KEY
open_ai_key="INSERT OPEN AI KEY"

[postgres]
host = "localhost"
port = 5432
dbname = "test"
user = "postgres"
password = "postgres"


